In [2]:
import numpy as np

class GaussianElimination:
    def __init__(self, A, b):
        """Initialize the class with matrix A and right-hand side vector b"""
        self.A = np.array(A, dtype=float)  # Coefficient matrix
        self.b = np.array(b, dtype=float)  # Right-hand side vector
        self.N = len(b)  # Number of equations (rows)
        
    def gaussian_elimination(self):
        """Perform Gaussian elimination"""
        for m in range(self.N):  # Loop through each row
            div = self.A[m, m]  # Get the diagonal element (pivot)
            self.A[m, :] /= div  # Normalize the row by dividing by the pivot
            self.b[m] /= div  # Normalize the right-hand side value
            
            # Eliminate the current column in the rows below
            for i in range(m+1, self.N):  # Loop through the rows below the current row
                mult = self.A[i, m]  # Get the multiplier to zero out the element
                self.A[i, :] -= mult * self.A[m, :]  # Subtract multiple of row m from row i
                self.b[i] -= mult * self.b[m]  # Subtract the corresponding value from b

    def back_substitution(self):
        """Perform back substitution to solve the system"""
        x = np.empty(self.N, dtype=float)  # Initialize the solution vector
        for m in range(self.N-1, -1, -1):  # Loop from the last row to the first
            x[m] = self.b[m]  # Start with the right-hand side value for the current row
            for i in range(m+1, self.N):  # Subtract known solutions from the current value
                x[m] -= self.A[m, i] * x[i]
        return x  # Return the solution vector

    def solve(self):
        """Solve the system using Gaussian elimination"""
        self.gaussian_elimination()  # Perform Gaussian elimination
        return self.back_substitution()  # Perform back substitution and return the solution

# Example usage
A = [[1, 1, 2, 1],  # Example system
     [2, 3, 1, 1],
     [1, 2, 3, 2],
     [3, 1, 2, 1]]
b = [9, 12, 15, 10]

# Initialize the GaussianElimination object
gauss = GaussianElimination(A, b)

# Solve the system
solution = gauss.solve()

print("Solution of the system (w, x, y, z):", solution)


Solution of the system (w, x, y, z): [0.5 2.5 2.5 1. ]


In [3]:
A = [[0, 1, 2, 1],  
     [2, 3, 1, 1],
     [1, 2, 3, 2],
     [3, 1, 2, 1]]
b = [9, 12, 15, 10]
N = len(b)  
gauss = GaussianElimination(A, b)

# Solve the system
solution = gauss.solve()

print("Solution of the system (w, x, y, z):", solution)

Solution of the system (w, x, y, z): [nan nan nan nan]


/tmp/ipykernel_113/4021689400.py:14: RuntimeWarning: divide by zero encountered in divide
  self.A[m, :] /= div  # Normalize the row by dividing by the pivot
/tmp/ipykernel_113/4021689400.py:14: RuntimeWarning: invalid value encountered in divide
  self.A[m, :] /= div  # Normalize the row by dividing by the pivot
/tmp/ipykernel_113/4021689400.py:15: RuntimeWarning: divide by zero encountered in scalar divide
  self.b[m] /= div  # Normalize the right-hand side value
/tmp/ipykernel_113/4021689400.py:15: RuntimeWarning: invalid value encountered in scalar divide
  self.b[m] /= div  # Normalize the right-hand side value


In [4]:
A = [[0, 7, 3, 5],
     [9, 0, 6, 2],
     [2, 8, 0, 1],
     [4, 3, 7, 0]]

b = [9, 12, 15, 10]
gauss = GaussianElimination(A, b)
solution = gauss.solve()

print("Solution of the system (w, x, y, z):", solution)


Solution of the system (w, x, y, z): [nan nan nan nan]


/tmp/ipykernel_113/4021689400.py:14: RuntimeWarning: divide by zero encountered in divide
  self.A[m, :] /= div  # Normalize the row by dividing by the pivot
/tmp/ipykernel_113/4021689400.py:14: RuntimeWarning: invalid value encountered in divide
  self.A[m, :] /= div  # Normalize the row by dividing by the pivot
/tmp/ipykernel_113/4021689400.py:15: RuntimeWarning: divide by zero encountered in scalar divide
  self.b[m] /= div  # Normalize the right-hand side value
/tmp/ipykernel_113/4021689400.py:15: RuntimeWarning: invalid value encountered in scalar divide
  self.b[m] /= div  # Normalize the right-hand side value


In [21]:
class GaussianEliminationSwap:
    def __init__(self, A, b):
        self.A = np.array(A, dtype=float)
        self.b = np.array(b, dtype=float)
        self.N = len(b)
        
    def swap_rows(self, m, i):
        self.A[[m, i], :] = self.A[[i, m], :]
        self.b[m], self.b[i] = self.b[i], self.b[m]
    
    def gaussian_elimination(self):
        for m in range(self.N):
            if self.A[m, m] == 0:
                for i in range(m+1, self.N):
                    if self.A[i, m] != 0:
                        self.swap_rows(m, i)
                        break
            
            div = self.A[m, m]
            self.A[m, :] /= div
            self.b[m] /= div
            
            for i in range(m+1, self.N):
                mult = self.A[i, m]
                self.A[i, :] -= mult * self.A[m, :]
                self.b[i] -= mult * self.b[m]

    def back_substitution(self):
        x = np.empty(self.N, dtype=float)
        for m in range(self.N-1, -1, -1):
            x[m] = self.b[m]
            for i in range(m+1, self.N):
                x[m] -= self.A[m, i] * x[i]
        return x

    def solve(self):
        self.gaussian_elimination()
        return self.back_substitution()

A = [[0, 7, 3, 5],
     [9, 0, 6, 2],
     [2, 8, 0, 1],
     [4, 3, 7, 0]]

b = [9, 12, 15, 10]

gauss = GaussianEliminationSwap(A, b)
solution = gauss.solve()

print("Solution of the system (w, x, y, z):", solution)


Solution of the system (w, x, y, z): [ 1.45263158  1.55368421 -0.06736842 -0.33473684]


In [11]:
# LU Decomposition function
def lu_decomposition(A):
    n = len(A)  # Get the size of the matrix A (number of rows/columns)
    L = np.zeros_like(A, dtype=float)  # Initialize an empty matrix L with the same shape as A
    U = np.zeros_like(A, dtype=float)  # Initialize an empty matrix U with the same shape as A
    
    # LU Decomposition process (computing the L and U matrices)
    for i in range(n):  # Loop over rows
        # Upper Triangular Matrix U
        for j in range(i, n):  # Loop over columns to fill the upper triangular matrix U
            # Calculate each element of U using the formula U[i, j] = A[i, j] - sum of the previous elements of L and U
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])
        
        # Lower Triangular Matrix L
        L[i, i] = 1  # The diagonal elements of L are 1 (by definition of L)
        for j in range(i+1, n):  # Loop over rows below the diagonal to fill the lower triangular matrix L
            # Calculate each element of L using the formula L[j, i] = (A[j, i] - sum of the previous elements of L and U) / U[i, i]
            L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]
    
    return L, U  # Return the L and U matrices

# Function for forward substitution to solve Ly = b
def forward_substitution(L, b):
    n = len(L)  # Get the size of matrix L
    y = np.zeros_like(b, dtype=float)  # Initialize the solution vector y with the same size as b
    
    for i in range(n):  # Loop through each row to solve for the elements of y
        # Solve for each element of y by subtracting the dot product of L and the already solved values of y
        # from the corresponding element in b
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    
    return y  # Return the solved vector y

# Function for back substitution to solve Ux = y
def back_substitution(U, y):
    n = len(U)  # Get the size of matrix U
    x = np.zeros_like(y, dtype=float)  # Initialize the solution vector x with the same size as y
    
    for i in range(n-1, -1, -1):  # Loop through the rows in reverse order (backward)
        # Solve for each element of x by subtracting the dot product of U and the already solved values of x
        # from the corresponding element in y
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    
    return x  # Return the solved vector x

# Given augmented matrix (including the right-hand side of the system)
A = np.array([[1, 1, 2, 1],  # Coefficients for the first equation
              [2, 3, 1, 1],  # Coefficients for the second equation
              [1, 2, 3, 2],  # Coefficients for the third equation
              [3, 1, 2, 1]], dtype=float)  # Coefficients for the fourth equation

b = np.array([9, 12, 15, 10], dtype=float)  # The right-hand side vector (b values of the system of equations)

# Perform LU Decomposition on matrix A
L, U = lu_decomposition(A)  # The LU Decomposition returns L and U matrices

# Solve Ly = b using forward substitution
y = forward_substitution(L, b)  # Find the intermediate solution vector y

# Solve Ux = y using back substitution
x = back_substitution(U, y)  # Find the final solution vector x, which contains the values of w, x, y, z

# Print the solution of the system (w, x, y, z)
print("Solution of the system (w, x, y, z):", x)  # Output the values of w, x, y, z


Solution of the system (w, x, y, z): [0.5 2.5 2.5 1. ]


In [20]:
A = np.array([[0, 1, 2, 1],  
              [2, 0, 1, 1],  
              [1, 2, 3, 2],  
              [3, 1, 2, 1]], dtype=float)  

b = np.array([9, 12, 15, 10], dtype=float)  

L, U = lu_decomposition(A)  
y = forward_substitution(L, b)  
x = back_substitution(U, y) 

print("Solution of the system (w, x, y, z):", x) 

Solution of the system (w, x, y, z): [nan nan nan nan]


/tmp/ipykernel_113/1651876467.py:18: RuntimeWarning: divide by zero encountered in scalar divide
  L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]
/tmp/ipykernel_113/1651876467.py:18: RuntimeWarning: invalid value encountered in scalar divide
  L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]


In [2]:
class LU_Decomposition_Solver:
    def __init__(self, A, b):
        self.A = np.array(A, dtype=float)
        self.b = np.array(b, dtype=float)
        self.N = len(b)

    def swap_rows(self, m, i):
        self.A[[m, i], :] = self.A[[i, m], :]
        self.b[m], self.b[i] = self.b[i], self.b[m]

    def lu_decomposition(self):
        n = len(self.A)
        L = np.zeros_like(self.A, dtype=float)
        U = np.zeros_like(self.A, dtype=float)

        for i in range(n):
            if self.A[i, i] == 0:  # Check for zero pivot
                for j in range(i+1, n):
                    if self.A[j, i] != 0:  # Swap rows if zero pivot is found
                        self.swap_rows(i, j)
                        break

            # Fill the upper triangular matrix U
            for j in range(i, n):
                U[i, j] = self.A[i, j] - np.dot(L[i, :i], U[:i, j])

            # Fill the lower triangular matrix L
            L[i, i] = 1
            for j in range(i+1, n):
                L[j, i] = (self.A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]

        return L, U

    def forward_substitution(self, L, b):
        y = np.zeros_like(b, dtype=float)
        for i in range(self.N):
            y[i] = b[i] - np.dot(L[i, :i], y[:i])
        return y

    def back_substitution(self, U, y):
        x = np.zeros_like(y, dtype=float)
        for i in range(self.N - 1, -1, -1):
            x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
        return x

    def solve(self):
        L, U = self.lu_decomposition()  # Perform LU Decomposition on A
        y = self.forward_substitution(L, self.b)  # Solve Ly = b
        x = self.back_substitution(U, y)  # Solve Ux = y
        return x

In [4]:
import numpy as np
A = np.array([[0, 1, 2, 1],  
              [2, 0, 1, 1],  
              [1, 2, 3, 2],  
              [3, 1, 2, 1]], dtype=float)  

b = np.array([9, 12, 15, 10], dtype=float) 


solver = LU_Decomposition_Solver(A, b)
solution = solver.solve()

print("Solution of the system (w, x, y, z):", solution)

Solution of the system (w, x, y, z): [ 0.33333333 -5.66666667  3.33333333  8.        ]


In [16]:
np.random.seed(42)  # Set a random seed for reproducibility
A = np.random.uniform(1, 10, (10, 10))  # 10x10 random matrix with floats between 1 and 10
A[0, 0] = 0  # Set the first diagonal element to zero as an example
b = np.random.uniform(1, 10, 10)  # 10x1 random vector with floats between 1 and 10

solver = LU_Decomposition_Solver(A, b)
solution = solver.solve()

print("Solution of the system (x1, x2, ..., x10):", solution)

Solution of the system (x1, x2, ..., x10): [-1.60503224 -0.42496614  1.03006282 -0.19515335 -2.03990386  2.69733886
  1.77923407 -2.14865848  1.08416375  0.87274357]


In [1]:
import numpy as np

def get_elimination_matrices(A):
    A = np.array(A, dtype=float)
    n = A.shape[0]
    L_steps = []
    A_current = A.copy()

    for k in range(n - 1):  # We do n-1 steps for n x n matrix
        Lk = np.identity(n)
        for i in range(k + 1, n):
            factor = A_current[i, k] / A_current[k, k]
            Lk[i, k] = -factor
            A_current[i, :] -= factor * A_current[k, :]

        L_steps.append(Lk)

    return L_steps, A_current

# Example 4x4 matrix
A = [
    [2, 1, 1, 3],
    [4, -6, 0, 2],
    [-2, 7, 2, 1],
    [6, -1, 5, 4]
]

L_steps, U = get_elimination_matrices(A)

# Display L0, L1, L2, L3
for i, Lk in enumerate(L_steps):
    print(f"L{i} =\n{Lk}\n")

print(f"Final Upper Triangular Matrix U =\n{U}")


L0 =
[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 1.  0.  1.  0.]
 [-3.  0.  0.  1.]]

L1 =
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 0.   1.   1.   0. ]
 [ 0.  -0.5  0.   1. ]]

L2 =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0. -3.  1.]]

Final Upper Triangular Matrix U =
[[ 2.  1.  1.  3.]
 [ 0. -8. -2. -4.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -3.]]


In [3]:
import numpy as np

def get_elimination_matrices(A):
    A = np.array(A, dtype=float)
    n = A.shape[0]
    L_steps = []
    A_current = A.copy()

    for k in range(n - 1):
        Lk = np.identity(n)
        for i in range(k + 1, n):
            factor = A_current[i, k] / A_current[k, k]
            Lk[i, k] = -factor
            A_current[i, :] -= factor * A_current[k, :]
        L_steps.append(Lk)

    return L_steps, A_current

def inverse_elementary(Lk):
    # Invert a lower triangular elimination matrix (just flip the signs)
    L_inv = np.identity(Lk.shape[0])
    for i in range(Lk.shape[0]):
        for j in range(i):
            L_inv[i, j] = -Lk[i, j]
    return L_inv

# Define a 4x4 matrix A and vector b
A = [
    [2, 1, 1, 3],
    [4, -6, 0, 2],
    [-2, 7, 2, 1],
    [6, -1, 5, 4]
]

b = [5, -2, 9, 4]

# Step 1: Get L0, L1, L2 and U
L_steps, U = get_elimination_matrices(A)

# Step 2: Build final L from inverses of L0, L1, L2
L = np.identity(len(A))
for Lk in reversed(L_steps):
    L_inv = inverse_elementary(Lk)
    L = L @ L_inv

# Step 3: Compute V = L @ U (should equal A)
V = L @ U

# Step 4: Display Results
print("A =")
print(np.array(A), "\n")

print("b =")
print(np.array(b), "\n")

for i, Lk in enumerate(L_steps):
    print(f"L{i} =")
    print(Lk, "\n")

# If L3 needed (for 4x4, usually not, but print identity for completeness)
if len(L_steps) < 4:
    print("L3 =")
    print(np.identity(4), "\n")

print("U =")
print(U, "\n")

print("Reconstructed V = L * U =")
print(V, "\n")


A =
[[ 2  1  1  3]
 [ 4 -6  0  2]
 [-2  7  2  1]
 [ 6 -1  5  4]] 

b =
[ 5 -2  9  4] 

L0 =
[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 1.  0.  1.  0.]
 [-3.  0.  0.  1.]] 

L1 =
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 0.   1.   1.   0. ]
 [ 0.  -0.5  0.   1. ]] 

L2 =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0. -3.  1.]] 

L3 =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

U =
[[ 2.  1.  1.  3.]
 [ 0. -8. -2. -4.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -3.]] 

Reconstructed V = L * U =
[[  2.   1.   1.   3.]
 [  4.  -6.   0.   2.]
 [ -6.   5.   0.  -5.]
 [-10.  15.   3.  -8.]] 



In [4]:
import numpy as np

class LU_Decomposition_Solver:
    def __init__(self, A, b):
        self.A = np.array(A, dtype=float)
        self.b = np.array(b, dtype=float)
        self.N = len(b)

    def get_elimination_matrices(self):
        n = self.N
        L_steps = []
        A_current = self.A.copy()

        for k in range(n - 1):
            Lk = np.identity(n)
            for i in range(k + 1, n):
                factor = A_current[i, k] / A_current[k, k]
                Lk[i, k] = -factor
                A_current[i, :] -= factor * A_current[k, :]
            L_steps.append(Lk)
        return L_steps, A_current

    def inverse_elementary(self, Lk):
        # Invert a lower triangular elimination matrix
        L_inv = np.identity(Lk.shape[0])
        for i in range(Lk.shape[0]):
            for j in range(i):
                L_inv[i, j] = -Lk[i, j]
        return L_inv

    def forward_substitution(self, L, b):
        y = np.zeros_like(b)
        for i in range(self.N):
            y[i] = b[i] - np.dot(L[i, :i], y[:i])
        return y

    def back_substitution(self, U, y):
        x = np.zeros_like(y)
        for i in range(self.N - 1, -1, -1):
            x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
        return x

    def solve(self):
        L_steps, U = self.get_elimination_matrices()

        # Build L from inverses
        L = np.identity(self.N)
        for Lk in reversed(L_steps):
            L_inv = self.inverse_elementary(Lk)
            L = L @ L_inv

        V = L @ U  # Reconstructed A

        y = self.forward_substitution(L, self.b)
        x = self.back_substitution(U, y)

        return {
            "A": self.A,
            "b": self.b,
            "L_steps": L_steps,
            "L": L,
            "U": U,
            "V": V,
            "solution": x
        }

# === INPUT ===
A = [
    [2, 1, 1, 3],
    [4, -6, 0, 2],
    [-2, 7, 2, 1],
    [6, -1, 5, 4]
]

b = [5, -2, 9, 4]

solver = LU_Decomposition_Solver(A, b)
result = solver.solve()

# === OUTPUT ===
np.set_printoptions(precision=3, suppress=True)

print("Original A =")
print(result["A"], "\n")

print("b =")
print(result["b"], "\n")

for i, Lk in enumerate(result["L_steps"]):
    print(f"L{i} =\n{Lk}\n")

if len(result["L_steps"]) < 4:
    print("L3 =\n", np.identity(4), "\n")

print("Final L =")
print(result["L"], "\n")

print("Final U =")
print(result["U"], "\n")

print("Reconstructed V = L · U ≈ A =")
print(result["V"], "\n")

w, x, y, z = result["solution"]
print(f"Solution: [w, x, y, z] = {result['solution']}")
print(f"w = {w:.4f}, x = {x:.4f}, y = {y:.4f}, z = {z:.4f}")


Original A =
[[ 2.  1.  1.  3.]
 [ 4. -6.  0.  2.]
 [-2.  7.  2.  1.]
 [ 6. -1.  5.  4.]] 

b =
[ 5. -2.  9.  4.] 

L0 =
[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 1.  0.  1.  0.]
 [-3.  0.  0.  1.]]

L1 =
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 0.   1.   1.   0. ]
 [ 0.  -0.5  0.   1. ]]

L2 =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0. -3.  1.]]

L3 =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

Final L =
[[ 1.   0.   0.   0. ]
 [ 2.   1.   0.   0. ]
 [-3.  -1.   1.   0. ]
 [-5.  -2.5  3.   1. ]] 

Final U =
[[ 2.  1.  1.  3.]
 [ 0. -8. -2. -4.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -3.]] 

Reconstructed V = L · U ≈ A =
[[  2.   1.   1.   3.]
 [  4.  -6.   0.   2.]
 [ -6.   5.   0.  -5.]
 [-10.  15.   3.  -8.]] 

Solution: [w, x, y, z] = [-18.167  -7.667  12.     12.333]
w = -18.1667, x = -7.6667, y = 12.0000, z = 12.3333


In [5]:
import numpy as np

def lu_decomposition(A):
    A = np.array(A, dtype=float)
    n = A.shape[0]
    L = np.eye(n)
    U = A.copy()

    for i in range(n):
        for j in range(i+1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            U[j, :] -= factor * U[i, :]
    
    return L, U

# Example matrix A
A = [
    [2, 1, 1, 3],
    [4, -6, 0, 2],
    [-2, 7, 2, 1],
    [6, -1, 5, 4]
]

# Perform LU decomposition
L, U = lu_decomposition(A)

# Reconstruct A
A_reconstructed = L @ U

# Display
np.set_printoptions(precision=3, suppress=True)

print("Original Matrix A =")
print(np.array(A), "\n")

print("Lower Triangular Matrix L =")
print(L, "\n")

print("Upper Triangular Matrix U =")
print(U, "\n")

print("Reconstructed Matrix (L @ U) =")
print(A_reconstructed, "\n")

# Check if reconstruction is accurate
print("Difference (A - L@U) =")
print(np.array(A) - A_reconstructed)


Original Matrix A =
[[ 2  1  1  3]
 [ 4 -6  0  2]
 [-2  7  2  1]
 [ 6 -1  5  4]] 

Lower Triangular Matrix L =
[[ 1.   0.   0.   0. ]
 [ 2.   1.   0.   0. ]
 [-1.  -1.   1.   0. ]
 [ 3.   0.5  3.   1. ]] 

Upper Triangular Matrix U =
[[ 2.  1.  1.  3.]
 [ 0. -8. -2. -4.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -3.]] 

Reconstructed Matrix (L @ U) =
[[ 2.  1.  1.  3.]
 [ 4. -6.  0.  2.]
 [-2.  7.  2.  1.]
 [ 6. -1.  5.  4.]] 

Difference (A - L@U) =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
